spring:
  config:
    activate:
      on-profile: k8s

  data:
    redis:
      host: ${REDIS_HOST:redis}
      port: ${REDIS_PORT:6379}

app:
  frontend:
    user-login-uri: ${USER_FRONTEND_LOGIN_URI}
    admin-login-uri: ${ADMIN_FRONTEND_LOGIN_URI}
