server:
  port: 9000

spring:
  application:
    name: spring-security-authorization-server

  data:
    redis:
      host: localhost
      port: 16379

  security:
    oauth2:
      authorizationserver:
        issuer: http://localhost:8080
        client:
          bff-client:
            registration:
              client-id: bff-client
              client-secret: "$2a$10$BDeXFNHccQiu0ef5vYr/Bu0fAjSQzCgKc5NBppHdETy1G.W4KJzbS"
              client-authentication-methods:
                - client_secret_basic
              authorization-grant-types:
                - authorization_code
                - refresh_token
              redirect-uris:
                - http://localhost:8080/bff/auth/callback
              post-logout-redirect-uris:
                - http://localhost:8080/
                - http://localhost:5173/login
              scopes:
                - openid
                - profile
            require-authorization-consent: false
            require-proof-key: false
  mail:
    host: smtp.example.com
    port: 587
#  mail:
#    host: smtp.example.com
#    port: 587
#    username: your-email@example.com
#    password: your-password
#    properties:
#      mail:
#        smtp:
#          auth: true
#          starttls:
#            enable: true

app:
  user-service:
    base-url: "http://localhost:8081"
  otp:
    expose-dev-otp: ${APP_OTP_EXPOSE_DEV_OTP:false}
    email:
      sender: dev
      ttl-seconds: 180
      resend-cooldown-seconds: 60
      max-verify-attempts: 5
    whatsapp:
      sender: ${APP_OTP_WHATSAPP_SENDER:dev}
      ttl-seconds: 180
      resend-cooldown-seconds: 60
      max-verify-attempts: 5
      graph-api-base-url: ${WHATSAPP_GRAPH_API_BASE_URL:https://graph.facebook.com/v25.0}
      phone-number-id: ${WHATSAPP_PHONE_NUMBER_ID:}
      access-token: ${WHATSAPP_ACCESS_TOKEN:}
      template-name: ${WHATSAPP_TEMPLATE_NAME:authentication_code_copy_code_button}
      language-code: ${WHATSAPP_LANGUAGE_CODE:en_US}
    webhook:
      whatsapp:
        verify-token: ${WHATSAPP_WEBHOOK_VERIFY_TOKEN:}
#  otp:
#    expose-dev-otp: false
#    email:
#      sender: smtp
#      from: "your-email@example.com"




logging:
  charset:
    console: UTF-8
  level:
    com.springmsa.authserver: debug
    org.springframework.security: trace