spring:
  config:
    activate:
      on-profile: local

  data:
    redis:
      host: localhost
      port: 16379

  security:
    oauth2:
      authorizationserver:
        issuer: http://localhost:8080
        client:
          bff-client:
            registration:
              client-id: bff-client
              client-secret: "$2a$10$BDeXFNHccQiu0ef5vYr/Bu0fAjSQzCgKc5NBppHdETy1G.W4KJzbS"
              client-authentication-methods:
                - client_secret_basic
              authorization-grant-types:
                - authorization_code
                - refresh_token
              redirect-uris:
                - http://localhost:8080/bff/auth/callback
              post-logout-redirect-uris:
                - http://localhost:8080/
                - http://localhost:5173/login
              scopes:
                - openid
                - profile
            require-authorization-consent: false
            require-proof-key: false

          admin-bff-client:
            registration:
              client-id: admin-bff-client
              client-secret: "$2a$10$Dm7Jh0Txq5XD7GRJXZSFFuIZQL1fMzpohFZJPM2EcFVPJNDsfveWi"
              client-authentication-methods:
                - client_secret_basic
              authorization-grant-types:
                - authorization_code
                - refresh_token
              redirect-uris:
                - http://localhost:8090/admin-bff/auth/callback
              post-logout-redirect-uris:
                - http://localhost:5176
                - http://localhost:5176/login
              scopes:
                - openid
                - profile
            require-authorization-consent: false
            require-proof-key: false

app:
  user-service:
    base-url: "http://localhost:8081"
