server:
  port: 9000
  forward-headers-strategy: framework
  servlet:
    session:
      cookie:
        name: AUTHSESSIONID
        http-only: true
        same-site: lax

spring:
  application:
    name: spring-security-authorization-server

  session:
    store-type: redis
    data:
      redis:
        namespace: spring:session:auth-server

logging:
  charset:
    console: UTF-8
  level:
    com.springmsa.authserver: debug
    org.springframework.security: trace

springmsa:
  internal-api:
    header-name: ${SPRING_MSA_INTERNAL_API_HEADER_NAME:X-Internal-Token}
    token: ${SPRING_MSA_INTERNAL_API_TOKEN:local-dev-internal-token}
